### ISSUE TITLE
Sidebar Top-Level 'open' when 'has-children'

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/podsio-genesis#17]
At present when you click on a top level you get this:
![screenshot 2016-07-15 12 57 48](https://cloud.githubusercontent.com/assets/3052875/16882214/cb014fa8-4a8b-11e6-82b9-1f9900f42739.png)

I'd prefer to see this:

![screenshot 2016-07-15 12 58 39](https://cloud.githubusercontent.com/assets/3052875/16882228/df8bdc9a-4a8b-11e6-93f1-0a294b8cf7c6.png)

**Comment by nicdford** [comment]
@jimtrue I'm just going to throw my css into the scss file... can you rule the compiler when you go to upload the changes? <3
